# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# CodeRabbit Configuration
# Documentation: https://docs.coderabbit.ai/

# Review Configuration
reviews:
  # High-level summary without excessive detail
  high_level_summary: true

  # Disable auto-request changes workflow to reduce noise
  request_changes_workflow: false

  # Disable review poems (optional aesthetic feature)
  poem: false

  # Review entire PR diff on every push (not just new commits)
  incremental_review: false

  # Auto-review settings
  auto_review:
    enabled: true
    drafts: false # Skip draft PRs during scaffolding

  # Branch filtering - ignore WIP and experimental branches
  # ignore_branches:
  #   - "wip/**"
  #   - "draft/**"
  #   - "experimental/**"
  #   - "poc/**"

  # Project-wide review instructions
  instructions: |
    This is an NX monorepo in early development/scaffolding phase.

    FOCUS reviews on:
    1. Package and dependency compatibility issues, especially between apps in apps/ and shared components in packages/
    2. Critical bugs and security vulnerabilities
    3. Architectural pattern violations
    4. Breaking changes to established APIs
    5. Logic errors and incorrect implementations
    6. Race conditions and concurrency issues

    SKIP or DEFER:
    - Style/formatting issues (handled by ESLint/Prettier)
    - TODOs and incomplete implementations
    - Premature performance optimizations
    - Missing documentation (until features are complete)
    - Minor naming suggestions
    - Trivial refactoring suggestions

    Be constructive and focus on high-impact issues only.

  # Path-based review instructions for targeted reviews
  path_instructions:
    - path: '**/*.ts'
      instructions: |
        Focus only on:
        - Critical bugs and security vulnerabilities
        - Performance issues that impact user experience
        - Breaking API changes
        - Logic errors
        Skip style/formatting issues if code follows existing patterns in the file.

    - path: '**/*.tsx'
      instructions: |
        Focus on:
        - Component architecture and patterns
        - React best practices (hooks, state management)
        - Accessibility concerns
        - Security issues (XSS, injection)
        Skip minor style suggestions.

    - path: '**/*.test.ts'
      instructions: |
        Review test coverage and correctness only.
        Skip minor naming suggestions.
        Focus on test logic and edge cases.

    - path: '**/*.spec.ts'
      instructions: |
        Review test coverage and correctness only.
        Skip minor naming suggestions.
        Focus on test logic and edge cases.

    - path: 'apps/**/*'
      instructions: |
        Focus on application-level concerns:
        - Architecture and structure
        - Security vulnerabilities
        - Performance bottlenecks
        - Dependency compatibility issues between apps and with shared components in packages/
        Skip trivial issues during scaffolding phase.

    - path: 'packages/**/*'
      instructions: |
        Focus on package/library design:
        - API design and contracts
        - Reusability patterns
        - Breaking changes
        - Dependency compatibility issues between in packages/ and with apps in apps/
        Skip incomplete implementations.

    - path: '**/project.json'
      instructions: |
        Review Nx project configuration for correctness.
        Check target configurations and dependencies.

    - path: 'nx.json'
      instructions: |
        Review workspace-level Nx configuration.
        Focus on task pipeline and caching configuration.

  # Change size thresholds - skip auto-review for very large PRs
  change_threshold:
    max_files: 50 # Don't auto-review PRs touching more than 50 files
    max_lines: 1000 # Don't auto-review PRs with more than 1000 lines changed

# Review filtering by severity
review_filters:
  # Only report warnings and errors, skip info-level suggestions
  severity_threshold: 'warning'

  # Ignore trivial issues
  ignore_trivial: true

# Language-specific settings
language_settings:
  typescript:
    # Use existing TypeScript, ESLint, and Prettier configurations
    use_existing_config: true

  javascript:
    use_existing_config: true

# Static Analysis Integration
static_analysis:
  # Respect existing linter and tool configurations
  respect_existing_rules: true

  # Tools to integrate with (CodeRabbit will respect their configs)
  tools:
    - eslint
    - prettier
    - typescript

  # Security: Secret Detection Patterns
  # NOTE: CodeRabbit uses Gitleaks which includes 100+ built-in patterns
  # Custom patterns below add project-specific detection for Supabase and database credentials
  security:
    secrets:
      enabled: true
      patterns:
        # Database credentials (PostgreSQL-specific for this project)
        - pattern: "(?i)(database_url|direct_url)\\s*=\\s*[\"\\']?postgresql://"
          message: "⚠️ Potential database credential detected. Ensure this is in .env files, not committed code."
          severity: high

        # Supabase credentials (project-specific patterns)
        - pattern: "(?i)(supabase.*key|anon.*key|service.*role.*key)\\s*=\\s*[\"\\']?[a-zA-Z0-9_-]{20,}"
          message: "⚠️ Potential Supabase API key detected. API keys should only be in .env files."
          severity: high

        # Generic API keys/tokens
        # Note: Gitleaks also detects generic secrets, but this provides custom message
        - pattern: "(?i)(api.*key|api.*token|access.*token)\\s*=\\s*[\"\\']?[a-zA-Z0-9_-]{20,}"
          message: "⚠️ Potential API key/token detected. Credentials should be in .env files."
          severity: medium

        # Password patterns
        # Note: Gitleaks has password detection, but this catches project-specific patterns
        - pattern: "(?i)(password|passwd|pwd)\\s*=\\s*[\"\\']?[^\"\\s]{8,}"
          message: "⚠️ Potential hardcoded password detected."
          severity: high

  # Path-based security filters
  path_filters:
    # Ignore .env.example files (templates are OK)
    - path: "**/.env*.example"
      exclude_patterns:
        - "(?i)(database_url|supabase.*key)"

# Chat settings
chat:
  # Allow interactive refinement of reviews
  auto_reply: false
